### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by andre6622** [BizzAppDev-Systems/connector-woocommerce#61]
Hi,
Great app! After installing and configuring: When I try to sync with WOO the jobs are waiting in the queue but not executed. Why and what can I do to get the queue started?

**Comment by bizzappdevteam** [comment]
Hello, @andre6622!

Thank you for reporting.
Indeed it is missing the configuration link in the documentation, we will add the configuration in our documentation soon.
Meanwhile, you can find the configuration [here](https://github.com/OCA/queue/tree/16.0/queue_job#configuration)

**Comment by bizzappdev** [comment]
Closing the issue as it was just a configuration. The link for the configuration has been shared.  [Link](https://github.com/OCA/queue/tree/16.0/queue_job#configuration)
